export const countryNames = [
    {name: "Afghanistan"},
    {name: "Australia"},
    {name: "Azerbaijan"},
    {name: "Japan"},
    {name: "Kyrgyzstan"},
    {name: "Malaysia"},
    {name: "Mexico"},
    {name: "New Zealand"},
    {name: "Pakistan"},
    {name: "Pitcairn"},
    {name: "Poland"},
    {name: "Portugal"},
    {name: "Qatar"},
    {name: "Russian"},
    {name: "Singapore"},
    {name: "Africa"},
    {name: "Spain"},
    {name: "Switzerland"},
    {name: "Syria"},
    {name: "Taiwan"},
    {name: "Tajikistan"},
    {name: "Thailand"},
    {name: "Trinidad and Tobago"},
    {name: "Turkey"},
    {name: "Turkmenistan"},
    {name: "Ukraine"},
    {name: "United Arab Emirates"},
    {name: "United Kingdom"},
    {name: "United States"},
    {name: "Uruguay"},
    {name: "Uzbekistan"},
]
